#!/bin/bash

p="fzf exa wget"
url="https://raw.githubusercontent.com/cx0y/wasd/main/code"

if [ "$1" == "i" ]
then
    sudo apt install $p #debian_based
    sudo dnf install $p #rpm_based
    sudo pacman -S $p #arch_based
    mkdir ~/.config/wasd/
    cd ~/.config/wasd/
    wget $url/wasdrc
    wget $url/url
    echo -e "Installation Complete"
    #echo -e "run: echo -e 'source ~/.config/wasd/wasdrc' >> <your_shell_rc>"
elif [ "$1" == "u" ]
then
    cd ~/.config
    rm -rf wasd
    cd ~
else
  exit 0
fi
