#!/bin/zsh

#config
BROWSER='xdg-open'
ENGINE='https://www.google.com/search?q='

#wasd-func
w(){
    #open web
    cd ~/.config/wasd
    $BROWSER "$(cat url | fzf)"
    cd ~
}

a(){
    #application luncher
    cd /usr/share/applications/
    gtk-launch $(fzf)
    cd ~
}

s(){
    #open file
    xdg-open "$(find -type f | fzf)"
}

d(){
    #open dir
    cd ~
    cd "$(find -type d | fzf)"
}

#others-func
dd(){
    #open dir in current path
    cd "$(find -type d | fzf)"
}

e(){
    # search form terminal
    echo -e "search:"
    read search
    $BROWSER $ENGINE${search// /+}  
}

fixpath(){
    #fixing broken path
    cd $(pwd)
    for i in *' '*; do mv "$i" `echo $i | sed -e 's/ /_/g'`; done
}

backup(){
    #backup current path
    mydir="$(basename $PWD)"
    sudo 7z a "$(date +"%Y%m%d").$mydir.7z" .
    mv -f *.7z ~
}

bookmark(){
    #add_bookmark_url
    echo -e "Enter Bookmark Url:"
    read url 
    echo -e $url >> ~/.config/wasd/url
}

#diff-func
confirm(){
    #!/usr/bin/env bash
    #confirmation_function_before_
    echo "About to execute $1 command"
    echo -n "Would you like to proceed y/n? "
    read reply
    if [ "$reply" = y -o "$reply" = Y ]
    then
        $1 "${@:2}"
    else
        echo "$1 ${@:2} cancelled"
    fi
}

#alias-path
alias home='cd ~' # go-to home
alias bin='cd /usr/local/bin/;exa' #go-to bin
alias lbin='cd ~/.local/bin/;exa' #go-to bin
alias ..='cd ..;pwd' #go-to up-dir
alias .2='cd ../../;pwd'
alias .3='cd ../../../;pwd'
alias .4='cd ../../../../;pwd'
alias .5='cd ../../../../../;pwd'

#alias-filesystem
alias ll='exa --long --header' #long list of path with header  
alias p='pwd' #path 
alias rm='rm -i' #rm with conformation 
alias du='du -sh * | sort -h' #file-folder size
#alias df='df -h' 
alias count='find . -type f | wc -l' #count total number of files
alias efdel='find -empty -type d -delete;find -empty -type f -delete' #delete_all_empty_files_folders

#alias-system
#alias tmux=''
alias root='confirm sudo su' #rooting terminal
alias mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort" #mounted devices
alias slp='confirm systemctl suspend' #sleeping
alias down='confirm shutdown now' #shut-down system 
alias open='xdg-open' #open file 

#alias-xclip
alias .='pwd | xclip -selection c ; echo -e "copied current path"' #copy_current_path
alias path="cd ~; find -type f | fzf | sed 's/^..//' | tr -d '\n' | xclip -selection c" #get files path
alias pathd="cd ~;find -type d | fzf | sed 's/^..//' | tr -d '\n' | xclip -selection c" #get folders path

#alias-git
git config --global alias.st 'status -sb' # git status - git st
git config --global alias.ll 'log --oneline' # git log - git ll
git config --global alias.last 'log -1 HEAD --stat' #git last commit - git last
git config --global alias.cm 'commit -m' #git commit - git cm
git config --global alias.rv 'remote -v' #git remote - git rv
git config --global alias.d 'diff' # git diff - git d
git config --global alias.se '!git rev-list --all | xargs git grep -F' #git search - git se <keyword>
git config --global help.autocorrect 20 #git autocorrect
git config --global alias.p 'push' #git push - git p
git config --global alias.a 'add' #git add - git a

#alias-others 
#alias cls='clear' #clear_by_cls
alias c='clear' #clear_by_c
alias x='confirm exit' #exit
alias backup_url='cp ~/config/wasd/url ~' #backup_url_file

